services:
  - type: web
    name: forensic-report-analyzer
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd app && gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
